apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: jmeter-slaves
spec:
  maxReplicas: 15
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jmeter-slaves # deployment name
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 90
